import { Testimonial, Service, DubaiArea } from "./types";

export const AGENT = {
  name: "Shahrukh Khan",
  company: "Pyramid Star Real Estate Brokerage",
  tagline: "Luxury Properties in Dubai",
  subtitle: "Your Trusted Partner in Dubai Real Estate",
  phone: "+971 55 823 1997",
  whatsapp: "971558231997",
  email: "shahrukhkhanshah1989@gmail.com",
  experience: "15+ Years",
  dealsClosed: "15,000+",
  license: "RERA Certified Agent | RERA 12735 | BRN (DLD) 40767",
  bio: "I, Shahrukh Khan, am a leading real estate specialist in Dubai, UAE, with over 15 years of proven excellence in the premium property market. I have built a strong reputation for delivering high-value investment opportunities and exclusive residential solutions in Dubai's most prestigious communities. Focused on results and client success, I provide end-to-end real estate services including buying, selling, and leasing luxury villas, high-rise apartments, and commercial properties. My expertise lies in identifying profitable opportunities and securing the best deals for both local and international investors. With deep market intelligence, strong negotiation skills, and access to Dubai's most exclusive listings, I ensure every client receives a seamless, transparent, and highly rewarding real estate experience. My commitment is simple: maximize value, minimize risk, and deliver exceptional outcomes in every transaction.",
  social: {
    instagram: "https://instagram.com/pyramidstar.ae",
    facebook: "https://www.facebook.com/pyramidstarre/",
    tiktok: "https://tiktok.com/@pyramidstar.ae",
  },
};

export const SKYCOURTS_TOWER = {
  developer: "National Bonds Corporation PJSC",
  cost: "AED 1.6 billion",
  units: "2,836 apartments across 6 towers",
  floors: "21 floors each",
  completed: 2010,
  height: "86.1 m (282 ft)",
  address:
    "Skycourts Tower - International City, Wadi Al Safa 5 - Sheikh Zayed Bin Hamdan Al Nahyan Street - Dubai",
  mapUrl: "https://maps.app.goo.gl/QAZxVSysJgL9LrBWA",
};

export const WHATSAPP_MESSAGE =
  "Hi Shahrukh! I'm interested in learning more about your luxury properties in Dubai with Pyramid Star Real Estate Brokerage. Can you share some options?";

export const SERVICES: Service[] = [
  {
    title: "Buying Assistance",
    description:
      "Find your dream property with expert guidance through every step of the purchasing process.",
    icon: "BsHouseCheck",
  },
  {
    title: "Renting Assistance",
    description:
      "Discover premium rental properties tailored to your lifestyle and budget requirements.",
    icon: "BsKey",
  },
  {
    title: "Investment Consulting",
    description:
      "Strategic investment advice to maximize returns in Dubai's dynamic real estate market.",
    icon: "BsGraphUpArrow",
  },
  {
    title: "Property Management",
    description:
      "Comprehensive management services to maintain and enhance the value of your properties.",
    icon: "BsBuilding",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Sharad More Shanaro Maruti",
    role: "Property Investor",
    rating: 5,
    text: "Shahrukh provided exceptional service and helped me secure a prime investment property. His deep knowledge of the Dubai market made all the difference.",
  },
  {
    id: "2",
    name: "Abhishek Trivedi",
    role: "Property Investor",
    rating: 5,
    text: "Very professional and knowledgeable. Shahrukh guided me through every step and found the perfect property that matched my investment goals.",
  },
  {
    id: "3",
    name: "Muhammad Javaid",
    role: "Property Investor",
    rating: 5,
    text: "Outstanding experience working with Shahrukh. He understood my requirements perfectly and delivered beyond expectations.",
  },
  {
    id: "4",
    name: "Muhammad Asif",
    role: "Property Investor",
    rating: 5,
    text: "Shahrukh is a true professional with extensive market knowledge. He made the entire process smooth and hassle-free.",
  },
  {
    id: "5",
    name: "Syed Azan Ullah",
    role: "Property Investor",
    rating: 5,
    text: "Highly recommended! Shahrukh went above and beyond to help me find the right property. His dedication and expertise are unmatched.",
  },
  {
    id: "6",
    name: "Asad Jan",
    role: "Home Buyer",
    rating: 5,
    text: "Shahrukh helped me buy my dream home in Dubai. From start to finish, he was incredibly supportive and made the process easy.",
  },
  {
    id: "7",
    name: "Syed Faizan Ullah",
    role: "Property Investor",
    rating: 5,
    text: "Great experience working with Shahrukh Khan. He is honest, reliable, and has excellent negotiation skills. Highly recommended!",
  },
  {
    id: "8",
    name: "Imran Khan",
    role: "Home Buyer",
    rating: 5,
    text: "Shahrukh made my home buying experience seamless and stress-free. His attention to detail and client-first approach is truly commendable.",
  },
];

export const DUBAI_AREAS: DubaiArea[] = [
  {
    name: "Skycourts Tower",
    description:
      "A project by National Bonds Corporation PJSC. AED 1.6 billion development offering 2,836 apartments across 6 towers. 21 floors each, completed in 2010.",
    image: "/images/Skycourts Tower.webp",
    slug: "skycourts-tower",
  },
  {
    name: "International City",
    description:
      "Wadi Al Safa 5 — Sheikh Zayed Bin Hamdan Al Nahyan Street. Well-connected community with access to Dubai Mall Metro Station via RTA route.",
    image: "/images/Building.webp",
    slug: "dubai-land-residence",
  },
  {
    name: "Skycourts Tower Amenities",
    description:
      "High-speed elevators, children's play area, landscaped surroundings, central air conditioning, well-maintained lobby, community gym, swimming pool, and jogging track.",
    image: "/images/Skycourts Tower evening Picture.jfif",
    slug: "skycourts-amenities",
  },
  {
    name: "Skycourts Tower Night View",
    description:
      "Experience stunning night views of the Dubai skyline from the tower's prime location in International City.",
    image: "/images/Skycourts Tower Night Picture.jfif",
    slug: "skycourts-night",
  },
];

export const PROPERTY_TYPES = [
  { value: "all", label: "All Types" },
  { value: "studio", label: "Studio" },
  { value: "apartment", label: "Apartment" },
  { value: "villa", label: "Villa" },
  { value: "commercial", label: "Commercial" },
];

export const PRICE_RANGES = [
  { value: "all", label: "Any Price" },
  { value: "0-30000", label: "Under AED 30K" },
  { value: "30000-50000", label: "AED 30K - 50K" },
  { value: "50000-80000", label: "AED 50K - 80K" },
  { value: "80000-120000", label: "AED 80K - 120K" },
  { value: "120000-999999", label: "AED 120K+" },
  { value: "1000000-2000000", label: "AED 1M - 2M" },
  { value: "2000000-999999999", label: "AED 2M+" },
];

export const LOCATIONS = [
  { value: "all", label: "All Locations" },
  { value: "Skycourts Tower - International City", label: "Skycourts Tower" },
  { value: "Skycourts Tower C - International City", label: "Skycourts Tower C" },
  { value: "International City", label: "International City" },
  { value: "Dubai Marina", label: "Dubai Marina" },
  { value: "Palm Jumeirah", label: "Palm Jumeirah" },
  { value: "Downtown Dubai", label: "Downtown Dubai" },
  { value: "Business Bay", label: "Business Bay" },
  { value: "Dubai Creek Harbour", label: "Dubai Creek Harbour" },
  { value: "Jumeirah Beach Residence (JBR)", label: "Jumeirah Beach Residence (JBR)" },
  { value: "Dubai Hills Estate", label: "Dubai Hills Estate" },
  { value: "Emirates Hills", label: "Emirates Hills" },
  { value: "Arabian Ranches", label: "Arabian Ranches" },
  { value: "Damac Hills", label: "Damac Hills" },
  { value: "Jumeirah Golf Estates", label: "Jumeirah Golf Estates" },
  { value: "Al Barari", label: "Al Barari" },
  { value: "The Springs", label: "The Springs" },
  { value: "The Meadows", label: "The Meadows" },
  { value: "The Lakes", label: "The Lakes" },
  { value: "Jumeirah Islands", label: "Jumeirah Islands" },
  { value: "Victory Heights", label: "Victory Heights" },
  { value: "Al Furjan", label: "Al Furjan" },
  { value: "Discovery Gardens", label: "Discovery Gardens" },
  { value: "Dubai Silicon Oasis", label: "Dubai Silicon Oasis" },
  { value: "Jumeirah Village Circle (JVC)", label: "Jumeirah Village Circle (JVC)" },
  { value: "Jumeirah Park", label: "Jumeirah Park" },
  { value: "Town Square", label: "Town Square" },
  { value: "Mudon", label: "Mudon" },
  { value: "Al Warqaa", label: "Al Warqaa" },
  { value: "Mirdif", label: "Mirdif" },
  { value: "Al Nahda", label: "Al Nahda" },
  { value: "Al Qusais", label: "Al Qusais" },
  { value: "Al Barsha", label: "Al Barsha" },
  { value: "Al Satwa", label: "Al Satwa" },
  { value: "Al Karama", label: "Al Karama" },
  { value: "Oud Metha", label: "Oud Metha" },
  { value: "Al Raffa", label: "Al Raffa" },
  { value: "Al Mankhool", label: "Al Mankhool" },
  { value: "Deira", label: "Deira" },
  { value: "Al Rigga", label: "Al Rigga" },
  { value: "Al Muraqqabat", label: "Al Muraqqabat" },
  { value: "Al Ghurair", label: "Al Ghurair" },
  { value: "Bur Dubai", label: "Bur Dubai" },
  { value: "Al Fahidi", label: "Al Fahidi" },
  { value: "Al Maktoum Road", label: "Al Maktoum Road" },
  { value: "Al Jafiliya", label: "Al Jafiliya" },
  { value: "Al Wasl", label: "Al Wasl" },
  { value: "Umm Suqeim", label: "Umm Suqeim" },
  { value: "Jumeirah 1", label: "Jumeirah 1" },
  { value: "Jumeirah 2", label: "Jumeirah 2" },
  { value: "Jumeirah 3", label: "Jumeirah 3" },
  { value: "Al Sufouh", label: "Al Sufouh" },
  { value: "Al Thanyah", label: "Al Thanyah" },
  { value: "The Greens", label: "The Greens" },
  { value: "Barsha Heights (TECOM)", label: "Barsha Heights (TECOM)" },
  { value: "Dubai Media City", label: "Dubai Media City" },
  { value: "Dubai Internet City", label: "Dubai Internet City" },
  { value: "Dubai Knowledge Park", label: "Dubai Knowledge Park" },
  { value: "Dubai Production City", label: "Dubai Production City" },
  { value: "Dubai Studio City", label: "Dubai Studio City" },
  { value: "Dubai Sports City", label: "Dubai Sports City" },
  { value: "Motor City", label: "Motor City" },
  { value: "Dubai Autodrome", label: "Dubai Autodrome" },
  { value: "Green Community", label: "Green Community" },
  { value: "Dubai Investment Park (DIP)", label: "Dubai Investment Park (DIP)" },
  { value: "Dubai World Central (DWC)", label: "Dubai World Central (DWC)" },
  { value: "Al Maktoum International Airport", label: "Al Maktoum International Airport" },
  { value: "Dubai South", label: "Dubai South" },
  { value: "Expo City Dubai", label: "Expo City Dubai" },
  { value: "The Palm Jebel Ali", label: "The Palm Jebel Ali" },
  { value: "Al Ghadeer", label: "Al Ghadeer" },
  { value: "Al Jaddaf", label: "Al Jaddaf" },
  { value: "Cultural Village", label: "Cultural Village" },
  { value: "Dubai Festival City", label: "Dubai Festival City" },
  { value: "Dubai Healthcare City", label: "Dubai Healthcare City" },
  { value: "Dubai Design District (d3)", label: "Dubai Design District (d3)" },
  { value: "Al Quoz", label: "Al Quoz" },
  { value: "Al Serkal Avenue", label: "Al Serkal Avenue" },
  { value: "Al Safa", label: "Al Safa" },
  { value: "Al Manara", label: "Al Manara" },
  { value: "Al Bada", label: "Al Bada" },
  { value: "Al Hudaiba", label: "Al Hudaiba" },
  { value: "Al Shindagha", label: "Al Shindagha" },
  { value: "Al Hamriya", label: "Al Hamriya" },
  { value: "Hor Al Anz", label: "Hor Al Anz" },
  { value: "Abu Hail", label: "Abu Hail" },
  { value: "Al Mamzar", label: "Al Mamzar" },
  { value: "Al Twar", label: "Al Twar" },
  { value: "Al Mizhar", label: "Al Mizhar" },
  { value: "Al Khawaneej", label: "Al Khawaneej" },
  { value: "Al Awir", label: "Al Awir" },
  { value: "Nad Al Shiba", label: "Nad Al Shiba" },
  { value: "Nad Al Hammar", label: "Nad Al Hammar" },
  { value: "Ras Al Khor", label: "Ras Al Khor" },
  { value: "Al Rashidiya", label: "Al Rashidiya" },
  { value: "Umm Ramool", label: "Umm Ramool" },
  { value: "Al Garhoud", label: "Al Garhoud" },
  { value: "Al Maktoum City", label: "Al Maktoum City" },
  { value: "Dubai Land Residence Complex", label: "Dubai Land Residence Complex" },
  { value: "Liwan", label: "Liwan" },
  { value: "Arjan", label: "Arjan" },
  { value: "Al Hebiah", label: "Al Hebiah" },
  { value: "Majan", label: "Majan" },
  { value: "Al Yalayis", label: "Al Yalayis" },
  { value: "Dubai Production City (IMPZ)", label: "Dubai Production City (IMPZ)" },
  { value: "Remraam", label: "Remraam" },
  { value: "The Villa", label: "The Villa" },
  { value: "Dubai Residential City", label: "Dubai Residential City" },
];
